### ISSUE TITLE
Error when running the birdie function with a mixed-effects formula

### ISSUE THREAD

**Issue by judah-axelrod** [CoryMcCartan/birdie#14]
Hi, when I run the toy example in the documentation, `r_probs` can be generated just fine using the `bisg` function, but I get the following error when I run the `birdie` function:
Error in levels(Y): object 'Y' not found

I've tried both
`fit = birdie(r_probs, turnout ~ (1 | proc_zip(zip)), data=pseudo_vf)`
and
`pseudo_vf$zip = proc_zip(pseudo_vf$zip)`
`fit = birdie(r_probs, turnout ~ (1 | zip), data=pseudo_vf)`

As best as I can tell it's an error with the em_mmm function but I'm not sure exactly why. I can get the complete-pooling and no-pooling versions to run fine - it's just the mixed model.

**Comment by CoryMcCartan** [comment]
Thanks for the bug report! 

Which version of `birdie` are you using?

**Comment by judah-axelrod** [comment]
I'm on version 0.3.1. And sorry about that! Reprex here:

``` r
library(birdie)
pseudo_vf$zip <- proc_zip(pseudo_vf$zip)
p_r = prop.table(table(pseudo_vf$race))
r_probs = bisg(~ nm(last_name) + zip(zip), data=pseudo_vf, p_r=p_r)
fit = birdie(r_probs, turnout ~ (1|zip), data=pseudo_vf)
#> Using default prior for Pr(X | R):
#> → Prior scale on fixed effects coefficients: 0.2
#> → Prior mean of random effects standard deviation: 0.10
#> This message is displayed once per session.
#> Error in levels(Y): object 'Y' not found
```

**Comment by CoryMcCartan** [comment]
Thanks! Was able to replicate. Sorry about that—I should move more development off the main branch now that it seems people are trying out the package.

If a fresh install from GitHub doesn't work (it should), I've now tagged the last version 0.3.0 (`remotes::install_github("CoryMcCartan/birdie@*release")`), which should be more stable.

**Comment by judah-axelrod** [comment]
Issue is fixed, thank you!
