### ISSUE TITLE
Example with census tracts?

### ISSUE THREAD

**Issue by davidmcclendon** [CoryMcCartan/birdie#17]
Hi! Love the package and looking forward to using it. I was hoping to use tracts instead of zip codes. I read through the documentation but can't quite get the formula right. I keep getting the error `Number of racial categories in `p_rgx` and `p_r` must match.` 

Can you provide an example? Thanks!

**Comment by CoryMcCartan** [comment]
Assuming you are building BISG probabilities only using names + tracts, you would provide e.g. `p_rgx =  census_race_geo_table("tract", state="DC")` to your `bisg()` call.   If that doesn't work, perhaps you can share the error message here and we can troubleshoot.

**Comment by davidmcclendon** [comment]
Thanks for the quick reply. Got it working. Posting it here for others:

`bisg(~ nm(surname) + GEOID, p_rgx = census_race_geo_table("tract", state="DC"), data=my_data)`
